name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install poetry
        run: |
          pip install poetry
          
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Activate virtual environemt
        run : |
          source .venv/bin/activate
          
      - name: Test with pytest
        run: |
          poetry run pytest --cov=ostatslib --cov-report=xml
      
      - name: Fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/<ostatslib>\/<ostatslib>\/<ostatslib>\//\/github\/workspace\//g' coverage.xml
          
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io
        with:
          # Additional arguments for the sonarcloud scanner
          args:             
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=OStatsAA_ostatslib
            -Dsonar.organization=ostatsaa
            -Dsonar.python.version=3
            -Dsonar.tests=tests
            -Dsonar.sources=ostatslib

      - name: Generate docs
        run: |
          jupyter-book build docs/
    
    # Push the book's HTML to github-pages
      - name: Publish Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
