name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install poetry
        run: |
          pip install poetry
      
      - name: Install dependencies
        run: |
          poetry install
          
      - name: Activate virtual environemt
        run : |
          source .venv/bin/activate
        
      - name: Set PYPI config
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_OSTATSLIB_TOKEN }}
      
      - name: Build and publish
        run: |
          poetry publish --build
    
